In [63]:
#import packages
import numpy as np
import pandas as pd


In [64]:
df=pd.read_csv('drug200.csv',delimiter=',')
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
5     22   F  NORMAL        HIGH    8.607  drugX
6     49   F  NORMAL        HIGH   16.275  drugY
7     41   M     LOW        HIGH   11.037  drugC
8     60   M  NORMAL        HIGH   15.171  drugY
9     43   M     LOW      NORMAL   19.368  drugY
10    47   F     LOW        HIGH   11.767  drugC
11    34   F    HIGH      NORMAL   19.199  drugY
12    43   M     LOW        HIGH   15.376  drugY
13    74   F     LOW        HIGH   20.942  drugY
14    50   F  NORMAL        HIGH   12.703  drugX
15    16   F    HIGH      NORMAL   15.516  drugY
16    69   M     LOW      NORMAL   11.455  drugX
17    43   M    HIGH        HIGH   13.972  drugA
18    23   M     LOW        HIGH    7.298  drugC
19    32   F    HIGH      NORMAL   25.974  drugY
20    57   M     LOW      NORMAL   19.128  drugY
21    63   M  NORMAL        HIGH   25.917  drugY
22    47   M     LOW      NORMAL   30.568  drugY
23    48   F     LOW        HIGH   15.036  drugY
24    33   F     LOW        HIGH   33.486  drugY
25    28   F    HIGH      NORMAL   18.809  drugY
26    31   M    HIGH        HIGH   30.366  drugY
27    49   F  NORMAL      NORMAL    9.381  drugX
28    39   F     LOW      NORMAL   22.697  drugY
29    45   M     LOW        HIGH   17.951  drugY
..   ...  ..     ...         ...      ...    ...
170   28   F  NORMAL        HIGH   12.879  drugX
171   45   M     LOW      NORMAL   10.017  drugX
172   39   F  NORMAL      NORMAL   17.225  drugY
173   41   F     LOW      NORMAL   18.739  drugY
174   42   M    HIGH      NORMAL   12.766  drugA
175   73   F    HIGH        HIGH   18.348  drugY
176   48   M    HIGH      NORMAL   10.446  drugA
177   25   M  NORMAL        HIGH   19.011  drugY
178   39   M  NORMAL        HIGH   15.969  drugY
179   67   F  NORMAL        HIGH   15.891  drugY
180   22   F    HIGH      NORMAL   22.818  drugY
181   59   F  NORMAL        HIGH   13.884  drugX
182   20   F     LOW      NORMAL   11.686  drugX
183   36   F    HIGH      NORMAL   15.490  drugY
184   18   F    HIGH        HIGH   37.188  drugY
185   57   F  NORMAL      NORMAL   25.893  drugY
186   70   M    HIGH        HIGH    9.849  drugB
187   47   M    HIGH        HIGH   10.403  drugA
188   65   M    HIGH      NORMAL   34.997  drugY
189   64   M    HIGH      NORMAL   20.932  drugY
190   58   M    HIGH        HIGH   18.991  drugY
191   23   M    HIGH        HIGH    8.011  drugA
192   72   M     LOW        HIGH   16.310  drugY
193   72   M     LOW        HIGH    6.769  drugC
194   46   F    HIGH        HIGH   34.686  drugY
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [65]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [66]:
#size of data
df.shape

(200, 6)

In [67]:
#for processing in sklearn convert into matrix
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [68]:
data_X=df[['Age','Sex','BP','Cholesterol','Na_to_K']].values
data_X
data_y=df[['Drug']].values

In [69]:
data_X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [70]:
#male and female also have effect in drug ...
#So converting it into Numerical data
# We can see from our data set that 3 varible have categories , so lets convert them into categories step by step
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data_X[:,1]=labelencoder.fit_transform(data_X[:,[1]])
data_X

C:\Users\vinod\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.113999999999999],
       [28, 0, 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 0, 'LOW', 'HIGH', 18.043],
       [22, 0, 'NORMAL', 'HIGH', 8.607000000000001],
       [49, 0, 'NORMAL', 'HIGH', 16.275],
       [41, 1, 'LOW', 'HIGH', 11.037],
       [60, 1, 'NORMAL', 'HIGH', 15.171],
       [43, 1, 'LOW', 'NORMAL', 19.368],
       [47, 0, 'LOW', 'HIGH', 11.767000000000001],
       [34, 0, 'HIGH', 'NORMAL', 19.199],
       [43, 1, 'LOW', 'HIGH', 15.376],
       [74, 0, 'LOW', 'HIGH', 20.941999999999997],
       [50, 0, 'NORMAL', 'HIGH', 12.703],
       [16, 0, 'HIGH', 'NORMAL', 15.515999999999998],
       [69, 1, 'LOW', 'NORMAL', 11.455],
       [43, 1, 'HIGH', 'HIGH', 13.972000000000001],
       [23, 1, 'LOW', 'HIGH', 7.297999999999999],
       [32, 0, 'HIGH', 'NORMAL', 25.974],
       [57, 1, 'LOW', 'NORMAL', 19.128],
       [63, 1, 'NORMAL', 'HIGH', 25.916999999999998],
  

In [71]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data_X[:,2]=labelencoder.fit_transform(data_X[:,[2]])
data_X

C:\Users\vinod\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[23, 0, 0, 'HIGH', 25.355],
       [47, 1, 1, 'HIGH', 13.093],
       [47, 1, 1, 'HIGH', 10.113999999999999],
       [28, 0, 2, 'HIGH', 7.797999999999999],
       [61, 0, 1, 'HIGH', 18.043],
       [22, 0, 2, 'HIGH', 8.607000000000001],
       [49, 0, 2, 'HIGH', 16.275],
       [41, 1, 1, 'HIGH', 11.037],
       [60, 1, 2, 'HIGH', 15.171],
       [43, 1, 1, 'NORMAL', 19.368],
       [47, 0, 1, 'HIGH', 11.767000000000001],
       [34, 0, 0, 'NORMAL', 19.199],
       [43, 1, 1, 'HIGH', 15.376],
       [74, 0, 1, 'HIGH', 20.941999999999997],
       [50, 0, 2, 'HIGH', 12.703],
       [16, 0, 0, 'NORMAL', 15.515999999999998],
       [69, 1, 1, 'NORMAL', 11.455],
       [43, 1, 0, 'HIGH', 13.972000000000001],
       [23, 1, 1, 'HIGH', 7.297999999999999],
       [32, 0, 0, 'NORMAL', 25.974],
       [57, 1, 1, 'NORMAL', 19.128],
       [63, 1, 2, 'HIGH', 25.916999999999998],
       [47, 1, 1, 'NORMAL', 30.568],
       [48, 0, 1, 'HIGH', 15.036],
       [33, 0, 1, 'HIGH', 33.486],
      

In [72]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data_X[:,3]=labelencoder.fit_transform(data_X[:,[3]])
data_X

C:\Users\vinod\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607000000000001],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767000000000001],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.941999999999997],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.515999999999998],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972000000000001],
       [23, 1, 1, 0, 7.297999999999999],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.916999999999998],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.95

In [73]:
data_X

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607000000000001],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767000000000001],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.941999999999997],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.515999999999998],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972000000000001],
       [23, 1, 1, 0, 7.297999999999999],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.916999999999998],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.95

In [74]:
data_X

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607000000000001],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767000000000001],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.941999999999997],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.515999999999998],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972000000000001],
       [23, 1, 1, 0, 7.297999999999999],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.916999999999998],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.95

In [75]:
df['BP'].value_counts()

HIGH      77
LOW       64
NORMAL    59
Name: BP, dtype: int64

In [76]:
data_X[1:5,:]

array([[47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [77]:
data_y=labelencoder.fit_transform(data_y)
data_y

C:\Users\vinod\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([4, 2, 2, 3, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 3, 4, 3, 0, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 3, 3, 0, 3, 3, 3, 4, 1, 4, 3,
       3, 3, 0, 2, 4, 4, 4, 3, 4, 4, 1, 2, 1, 4, 3, 4, 4, 0, 4, 3, 1, 4,
       0, 3, 4, 4, 1, 4, 3, 4, 4, 4, 0, 4, 0, 3, 1, 3, 2, 0, 2, 1, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 0, 2, 3, 4, 3, 3, 4, 1, 4,
       0, 3, 3, 3, 3, 4, 3, 3, 0, 4, 4, 4, 4, 4, 1, 4, 4, 3, 4, 3, 4, 4,
       3, 4, 4, 3, 1, 0, 1, 3, 0, 4, 1, 4, 0, 3, 3, 0, 3, 2, 0, 1, 3, 3,
       4, 2, 0, 4, 2, 3, 3, 1, 3, 4, 4, 4, 4, 3, 4, 0, 3, 3, 4, 4, 0, 4,
       0, 4, 4, 4, 4, 3, 3, 4, 4, 4, 1, 0, 4, 4, 4, 0, 4, 2, 4, 2, 2, 3,
       3, 3], dtype=int32)

In [102]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(data_X,data_y,test_size=.3,random_state=3)
classifier = DecisionTreeClassifier(criterion='entropy',max_depth=4)

classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [103]:
y_pred=classifier.predict(X_test)
y_pred

array([4, 3, 3, 3, 3, 2, 4, 0, 1, 0, 4, 0, 4, 4, 3, 4, 3, 3, 1, 3, 3, 4,
       4, 4, 3, 1, 4, 4, 0, 3, 1, 2, 2, 3, 3, 2, 4, 3, 3, 3, 0, 4, 2, 4,
       0, 4, 4, 4, 4, 4, 1, 3, 4, 3, 4, 4, 0, 3, 4, 3], dtype=int32)

In [104]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9833333333333333

ModuleNotFoundError: No module named 'pydotplus'